--- #YAML:1.0
name:                Devel-Events-Objects
version:             0.01
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Devel::Events:                 0
    Task::Weaken:                  0
    Test::Exception:               0
    Test::use::ok:                 0
    Tie::RefHash::Weak:            0.06
    Variable::Magic:               0.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
